# Generated by Django 5.1.7 on 2025-04-27 17:44

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('int_enum', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(1, 'Minimum'), (2, 'Medium'), (3, 'Maximum')], default=1)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('int_enum__in', [1, 2, 3])), name='leusis_Todo_int_enum_PriorityEnum')],
            },
        ),
    ]
