# Generated by Django 5.1.7 on 2025-04-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leusis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='todo',
            name='leusis_Todo_int_enum_PriorityEnum',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='int_enum',
            new_name='priority',
        ),
        migrations.AddConstraint(
            model_name='todo',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', [1, 2, 3])), name='leusis_Todo_priority_PriorityEnum'),
        ),
    ]
