# Generated by Django 5.1.7 on 2025-03-14 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_generalsensor_waterlevelsensor_delete_sensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsensor',
            name='data',
        ),
        migrations.RemoveField(
            model_name='waterlevelsensor',
            name='current_level',
        ),
        migrations.CreateModel(
            name='GeneralSensorValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('date', models.DateTimeField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.generalsensor')),
            ],
        ),
        migrations.CreateModel(
            name='WaterLevelSensorValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.FloatField()),
                ('date', models.DateTimeField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.waterlevelsensor')),
            ],
        ),
    ]
