# Generated by Django 5.1.7 on 2025-03-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_generalsensorvalues_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsensor',
            name='sensor_type',
            field=models.CharField(default='general', max_length=100),
            preserve_default=False,
        ),
    ]
