# Generated by Django 5.1.7 on 2025-03-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_notifieduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsensor',
            name='max_value',
            field=models.FloatField(default=15),
        ),
        migrations.AddField(
            model_name='generalsensor',
            name='min_value',
            field=models.FloatField(default=1),
        ),
    ]
