# Generated by Django 5.1.7 on 2025-03-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_poi_question_quiz_reward_stores_delete_notifieduser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stores',
            name='lon',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
