# Generated by Django 5.1.7 on 2025-03-28 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_reward_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.stores'),
            preserve_default=False,
        ),
    ]
