# Generated by Django 5.1.7 on 2025-03-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_reward_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='code',
            field=models.CharField(default='---', max_length=100),
            preserve_default=False,
        ),
    ]
